const DEFAULT_DELAY = 1000;
const DEFAULT_DURATION = 2000;
const DEFAULT_IS_INFINITE_ANIMATION = false;
const DEFAULT_EASE_STYLE = 'linear';

export {
  DEFAULT_DELAY,
  DEFAULT_DURATION,
  DEFAULT_IS_INFINITE_ANIMATION,
  DEFAULT_EASE_STYLE,
};
